// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT9MiVWjxQSzUU9DqKabB1OKFp0Gm0VDc',
    appId: '1:491181308224:web:8eb489c2bc723ac34b62a5',
    messagingSenderId: '491181308224',
    projectId: 'proekt-b7928',
    authDomain: 'proekt-b7928.firebaseapp.com',
    storageBucket: 'proekt-b7928.appspot.com',
    measurementId: 'G-ZYKD2B7P1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVUyRfynnC5DXb1OvpI_JHA6xVYhwUUI',
    appId: '1:491181308224:android:017801d0920cd9b24b62a5',
    messagingSenderId: '491181308224',
    projectId: 'proekt-b7928',
    storageBucket: 'proekt-b7928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA89NgXCvTl3ksq8cIsXzMioxDgl45PGOo',
    appId: '1:491181308224:ios:f22d9557abb0005c4b62a5',
    messagingSenderId: '491181308224',
    projectId: 'proekt-b7928',
    storageBucket: 'proekt-b7928.appspot.com',
    iosBundleId: 'com.example.proekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA89NgXCvTl3ksq8cIsXzMioxDgl45PGOo',
    appId: '1:491181308224:ios:f22d9557abb0005c4b62a5',
    messagingSenderId: '491181308224',
    projectId: 'proekt-b7928',
    storageBucket: 'proekt-b7928.appspot.com',
    iosBundleId: 'com.example.proekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT9MiVWjxQSzUU9DqKabB1OKFp0Gm0VDc',
    appId: '1:491181308224:web:b29eb185f17f222a4b62a5',
    messagingSenderId: '491181308224',
    projectId: 'proekt-b7928',
    authDomain: 'proekt-b7928.firebaseapp.com',
    storageBucket: 'proekt-b7928.appspot.com',
    measurementId: 'G-WR8TQD2WSD',
  );

}